<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

	<xsl:output method="xml"
	            doctype-public="-//W3C//DTD XHTML 1.1//EN"
	            doctype-system="http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"
	            indent="yes"/>

	<xsl:param name="descriptor"/>
	<xsl:param name="host"/>

	<xsl:template match="/">
		<html>
			<head>
				<title>FreeCast Network | Welcome Page</title>
				<script type="text/javascript" src="http://www.freecast.org/start.js">
					/* must NOT be empty because of IE */
				</script>
				<link href="data/start.css" rel="stylesheet" type="text/css" media="screen" title="FreeCast"/>
			</head>
			<body>
				<div id="container">
					<div id="branding">
						<div id="logo">
							<a href=".">
								<img src="data/freecast.png" alt=""/>
							</a>
						</div>
						<div id="tool">
							<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
						</div>
					</div>
					<div id="content">
						<h1>Welcome to this FreeCast Test Network</h1>
						<div class="summary">
							This page is automaticaly generated by <strong>FreeCast Manager</strong> to allow you
							to join this FreeCast Test Network.
						</div>
						<h3>Start your FreeCast listener node</h3>
						<p>
							To start FreeCast, just
							<a>
								<xsl:attribute name="href">
									<xsl:text>javascript:start('</xsl:text>
									<xsl:value-of select="$descriptor"/>
									<xsl:text>')</xsl:text>
								</xsl:attribute>
								<xsl:text>click and listen</xsl:text>
							</a>
							.
						</p>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>